import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/navigation/Header";
import ImageProcessor from "@/components/ImageProcessor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <hr className="w-[90%] mx-auto rounded-full border-[#242424]"/>
        <div>{children}</div>
      </body>
    </html>
  );
}
